cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'ag'
brew 'antigen'
brew 'diff-so-fancy'
brew 'grc'
brew 'node'
brew 'unrar'

cask '1password'
cask 'atom'
cask 'cyberduck'
cask 'docker'
cask 'dropbox'
cask 'google-chrome'
cask 'poedit'
cask 'postgres'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'vlc'
